@echo off

REM ============================================================
REM  iscsi-creds.cmd
REM  iSCSI credentials loaded by iscsi-connect.cmd and dism-install.cmd.
REM
REM  Placeholder values are substituted at deploy time by
REM  efiDeployScripts/deploy.sh — do not edit this file directly.
REM
REM  This file is served via iPXE initrd at boot time and lands
REM  at %SYSTEMDRIVE%\Windows\System32\iscsi-creds.cmd in WinPE.
REM ============================================================

REM ── iSCSI Target LUN (win-lvrgamingpc) ──────────────────────
REM  The disk Windows is installed to and booted from.
REM  All variables in this section are required.

REM  Target portal address, port, and IQN
set ISCSI_PORTAL=%%ISCSI_PORTAL%%
set ISCSI_PORT=%%ISCSI_PORT%%
set ISCSI_IQN=%%ISCSI_IQN%%

REM  CHAP: initiator authenticates TO the target
set ISCSI_USER=%%ISCSI_USER%%
set ISCSI_PASS=%%ISCSI_PASS%%

REM  Mutual CHAP: target authenticates BACK to the initiator
set ISCSI_CHAP_SECRET=%%ISCSI_CHAP_SECRET%%

REM ── Install Source LUN (windows-installation) ───────────────
REM  Read-only LUN containing the extracted Windows 11 ISO.
REM  Used only by the DISM install path (dism-install.cmd).
REM
REM  INSTALL_PORTAL and INSTALL_PORT are optional: leave empty to
REM  inherit ISCSI_PORTAL and ISCSI_PORT (same server). Set a value
REM  only if the install source LUN is on a different server or port.

REM  Target portal address and port (optional — see note above)
set INSTALL_PORTAL=%%INSTALL_PORTAL%%
set INSTALL_PORT=%%INSTALL_PORT%%

REM  Target IQN
set INSTALL_IQN=%%INSTALL_IQN%%

REM  CHAP: initiator authenticates TO the target
set INSTALL_USER=%%INSTALL_USER%%
set INSTALL_PASS=%%INSTALL_PASS%%

REM  Mutual CHAP: target authenticates BACK to the initiator
set INSTALL_CHAP_SECRET=%%INSTALL_CHAP_SECRET%%
